version: '3.0'
services:
  postgres:
    restart: 'always'
    environment:
      - "POSTGRES_USER=weatheruser"
      - "POSTGRES_DB=weatherdb"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - /tmp/postgresdata:/var/lib/postgresql/data
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
  weathercollector:
    restart: 'always'
    ports:
      - '7888:7888'
    environment:
      - "OPEN_WEATHER_MAP_API_KEY=${OPEN_WEATHER_MAP_API_KEY}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=postgres"
    build:
      context: ./weathercollector/
      dockerfile: Dockerfile